steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/masterd/${_IMAGE}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/masterd/${_IMAGE}']
images:
- 'europe-west2-docker.pkg.dev/$PROJECT_ID/masterd/${_IMAGE}'
